apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: dev-control
  namespace: dev
spec:
  selector: all()
  types:
    - Egress
  egress:
  - action: Deny
    destination:
      selector: role == "deny"
