apiVersion: crd.projectcalico.org/v1
kind: NetworkPolicy
metadata:
  name: default.dev-control
  namespace: dev
spec:
  order: 100
  selector: app == "netshoot"
  types:
    - Egress
  egress:
  - action: Deny
    destination:
      selector: role == "deny" 
  - action: Allow
    destination:
      selector: role == "allow"